name: frangof
description: "Aplicativo Frango do Vizinho"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Backend
  supabase_flutter: ^2.10.3

  # UI e utilidades
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.4
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
  
   - lib/assets/images/  

